---

base_archiving_tools:
  - arj            # ARJ archiver
  - cabextract     # Extracts Microsoft cabinet files
  - file-roller    # GNOME archive manager
  - mpack          # MIME mail packer/unpacker
  - p7zip-full     # 7z archive support
  - sharutils      # Shell archiving utilities
  - unace          # Extracts ACE archives
  - unzip          # Extracts ZIP archives
  - uudeview       # UUencoded file decoder
  - zip            # ZIP archive tool

base_productivity_tools:
  - libreoffice    # Office suite

base_system_tools:
  - bind9-dnsutils  # DNS utilities
  - gnome-calculator  # Calculator application for GNOME
  - lsd  # the next gen `ls` command
  - network-manager-openvpn-gnome  # Network Manager VPN plugin for OpenVPN
  - openvpn  # VPN client
  - qemu-guest-agent  # Guest agent for QEMU/KVM
  - spice-vdagent  # Guest agent for SPICE
  - strace  # System call tracer
  - rsync  # Fast, versatile, remote (and local) file-copying tool

base_download_tools:
  - aria2  # Lightweight multi-protocol & multi-source command-line download utility
  - wget  # Network downloader

base_developer_tools:
  - alacritty  # OpenGL terminal emulator
  - bat  # A cat(1) clone with wings
  - btop  # Modern and colorful command line resource monitor that shows usage and stats
  - cargo  # Rust package manager
  - curl  # Command line tool for transferring data with URL syntax
  - dos2unix  # Convert text files with DOS or Mac line endings to Unix line endings
  - entr  # Run arbitrary commands when files change
  - expect  # Automate interactive applications
  - fzf  # A command-line fuzzy finder
  - glow  # Redder Markdown on the command-line
  - g++  # GNU C++ compiler
  - gawk  # GNU version of AWK programming language
  - git  # Distributed version control system
  - git-extras  # GIT utilities -- provides git summary, git changelog, git effort, etc.
  - golang-go  # Go programming language compiler and tools
  - htop  # Interactive process viewer
  - httpie  # User-friendly command-line HTTP client
  - jq  # Command-line JSON processor
  - meld  # Visual diff and merge tool
  - moreutils  # Collection of useful UNIX utilities
  - mtr-tiny  # Network diagnostic tool
  - nmap  # Network exploration tool and security/port scanner
  - pandoc  # universal document converter
  - parallel  # Shell tool for executing jobs in parallel
  - pipx  # Install and run Python applications in isolated environments
  - pv  # Pipe viewer - monitor the progress of data through a pipeline
  - pylint  # Python code static checker
  - python3-pep8  # Python style guide checker
  - python3-pip  # Python package installer
  - python3-poetry  # Python dependency management and packaging made easy
  - tcptraceroute  # traceroute implementation using TCP packets
  - tmux  # terminal multiplexer
  - tree  # display directories as trees (with optional color/HTML output)
  - xh  # A friendly and fast curl alternative
  - xsel  # Command-line program for getting and setting the contents of the X selection

# uses pipx to install python pip packages in a virtualized environment
base_developer_tools_pipx:
  - tldr  # Simplified and community-driven man pages
  - ruff  # Extremely fast Python linter, written in Rust
  - mitmproxy  # An interactive, SSL-capable intercepting proxy for HTTP with a console interface

base_media_tools:
  - ffmpeg  # Multimedia framework for handling audio, video, and other multimedia files and streams
  - imagemagick  # Software suite to create, edit, compose, or convert bitmap images
  - libimage-exiftool-perl  # Read, write and edit meta information in image, audio and video files
  - vlc  # Multi-platform multimedia player and streamer

...
