---

terminal_customizations_nerd_fonts_version: v3.4.0  # TODO: bump up version number as newer versions are made avaialbe from source git repo https://github.com/ryanoasis/nerd-fonts/releases/
terminal_customizations_nerd_fonts_base_url: "https://github.com/ryanoasis/nerd-fonts/raw/{{ terminal_customizations_nerd_fonts_version }}/patched-fonts"

# nerd fonts from https://github.com/ryanoasis/nerd-fonts
terminal_customizations_nerd_fonts:
  - "{{ terminal_customizations_nerd_fonts_base_url }}/CascadiaCode/CaskaydiaCoveNerdFontMono-BoldItalic.ttf"  # don't remove; alacritty config uses this
  - "{{ terminal_customizations_nerd_fonts_base_url }}/CascadiaCode/CaskaydiaCoveNerdFontMono-Bold.ttf"        # don't remove; alacritty config uses this
  - "{{ terminal_customizations_nerd_fonts_base_url }}/CascadiaCode/CaskaydiaCoveNerdFontMono-Italic.ttf"      # don't remove; alacritty config uses this
  - "{{ terminal_customizations_nerd_fonts_base_url }}/CascadiaCode/CaskaydiaCoveNerdFontMono-Regular.ttf"     # don't remove; alacritty config uses this
  - "{{ terminal_customizations_nerd_fonts_base_url }}/SourceCodePro/SauceCodeProNerdFontMono-BoldItalic.ttf"
  - "{{ terminal_customizations_nerd_fonts_base_url }}/SourceCodePro/SauceCodeProNerdFontMono-Bold.ttf"
  - "{{ terminal_customizations_nerd_fonts_base_url }}/SourceCodePro/SauceCodeProNerdFontMono-Italic.ttf"
  - "{{ terminal_customizations_nerd_fonts_base_url }}/SourceCodePro/SauceCodeProNerdFontMono-Regular.ttf"

terminal_customizations_tmux_plugin_repo: "https://github.com/tmux-plugins/tpm"

terminal_customizations_alacritty_themes_repo: "https://github.com/alacritty/alacritty-theme"

...
