---

zsh_packages:
  - zsh          # Z shell, a powerful interactive shell and scripting language
  - fzf

zsh_zinit_git_repo: "https://github.com/zdharma-continuum/zinit.git"
zsh_zinit_install_path: "~/.local/share/zinit/zinit.git"

...
